### ISSUE TITLE
CopyNuGetImplementations should only be set for some projects

### ISSUE THREAD

**Issue by clairernovotny** [wgtmpeters/nugetprojectjson#1]
Most project types should not have `CopyNuGetImplementations` set to true. Enabling that does copy libs to the output directory but that's unnecessary for most library projects in a solution.

Projects that _should_ have it set are:
- Test projects with NUnit, xUnit or MSTest
- Executables (services, appx, xap)
- ASP.Net  that aren't ASPNet 5.0

**Comment by wgtmpeters** [comment]
Removed the property from the script.
